# Build target untuk ESP32-S3 bare-metal (no_std)
[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
# rustflags tidak diperlukan — esp-hal/xtensa-lx-rt handle linker script via build script

[unstable]
build-std = ["core", "alloc"]
